### ISSUE TITLE
Cannot deploy to ShinyApps

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/PRISMA2020#13]
Receive the error 'Unable to find repository URL for package' when trying to deploy using rsconnect::deployApp(). Ping @chriscpritchard.

**Comment by chriscpritchard** [comment]
Does it say which package?

**Comment by chriscpritchard** [comment]
Can you try changing:
[app.R](https://github.com/nealhaddaway/PRISMA2020/blob/master/inst/shiny-examples/PRISMA_flowdiagram/app.R)
```R
if(!require(PRISMA2020)) {
  devtools::install_github("nealhaddaway/PRISMA2020")
}
library(PRISMA2020)
```
to
```R
devtools::install_github("nealhaddaway/PRISMA2020")
library(PRISMA2020)
```
and let me know if that works when you push it

**Comment by nealhaddaway** [comment]
Hmm - no - same error, plus this warning: 'Package 'PRISMA2020 0.0.2' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores'
________________________________

**Comment by chriscpritchard** [comment]
I have no idea why it's not working, I just tried it and it works fine (https://chriscpritchard.shinyapps.io/prisma_flowdiagram/)

Can you send me / upload on here the entire log message from your attempt to upload so I can look at it in a bit more detail?

**Comment by nealhaddaway** [comment]
Sure - here it is in full - it seems to be looking to CRAN for the package...

---
> rsconnect::deployApp()
Preparing to deploy application...
Update application currently deployed at
https://estech.shinyapps.io/prisma_flowdiagram/? [Y/n] Y
DONE
Uploading bundle for application: 3345280...Bioconductor version 3.12 (BiocManager 1.30.12), ?BiocManager::install for help
Bioconductor version '3.12' is out-of-date; the current release version '3.13' is available with R version '4.1'; see https://bioconductor.org/install
Warning in FUN(X[[i]], ...) :
  Unable to find repository URL for package PRISMA2020
DONE
Deploying bundle: 4795176 for application: 3345280 ...
Waiting for task: 966721636
  building: Parsing manifest
  building: Building image: 5499813
  building: Installing system dependencies
  building: Fetching packages
  error: Building package: PRISMA2020
################################ Begin Task Log ################################
[2021-07-07T10:04:14.291974538+0000] Execute script: packages/build/igraph.sh
+ set -e
+ apt-get update -qq
+ apt-get install -y libglpk-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libamd2 libbtf1 libcamd2 libccolamd2 libcholmod3 libcolamd2 libcxsparse3
  libglpk40 libgmp-dev libgmpxx4ldbl libgraphblas3 libklu1 libldl2 libmetis5
  libmongoose2 librbio2 libspqr2 libsuitesparse-dev libsuitesparseconfig5
  libumfpack5
Suggested packages:
  libiodbc2-dev gmp-doc libgmp10-doc libmpfr-dev
The following NEW packages will be installed:
  libamd2 libbtf1 libcamd2 libccolamd2 libcholmod3 libcolamd2 libcxsparse3
  libglpk-dev libglpk40 libgmp-dev libgmpxx4ldbl libgraphblas3 libklu1 libldl2
  libmetis5 libmongoose2 librbio2 libspqr2 libsuitesparse-dev
  libsuitesparseconfig5 libumfpack5
0 upgraded, 21 newly installed, 0 to remove and 57 not upgraded.
Need to get 10.2 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libsuitesparseconfig5 amd64 1:5.7.1+dfsg-2 [9736 B]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libamd2 amd64 1:5.7.1+dfsg-2 [20.0 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libbtf1 amd64 1:5.7.1+dfsg-2 [11.3 kB]
Get:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libcamd2 amd64 1:5.7.1+dfsg-2 [21.7 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libccolamd2 amd64 1:5.7.1+dfsg-2 [23.2 kB]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libcolamd2 amd64 1:5.7.1+dfsg-2 [17.0 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libmetis5 amd64 5.1.0.dfsg-5 [169 kB]
Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libcholmod3 amd64 1:5.7.1+dfsg-2 [308 kB]
Get:9 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libcxsparse3 amd64 1:5.7.1+dfsg-2 [64.2 kB]
Get:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libglpk40 amd64 4.65-2 [378 kB]
Get:11 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libgmpxx4ldbl amd64 2:6.2.0+dfsg-4 [9128 B]
Get:12 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libgmp-dev amd64 2:6.2.0+dfsg-4 [320 kB]
Get:13 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libgraphblas3 amd64 1:5.7.1+dfsg-2 [3770 kB]
Get:14 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libklu1 amd64 1:5.7.1+dfsg-2 [71.7 kB]
Get:15 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libldl2 amd64 1:5.7.1+dfsg-2 [11.0 kB]
Get:16 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libmongoose2 amd64 1:5.7.1+dfsg-2 [31.4 kB]
Get:17 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libumfpack5 amd64 1:5.7.1+dfsg-2 [229 kB]
Get:18 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 librbio2 amd64 1:5.7.1+dfsg-2 [24.5 kB]
Get:19 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libspqr2 amd64 1:5.7.1+dfsg-2 [64.8 kB]
Get:20 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libsuitesparse-dev amd64 1:5.7.1+dfsg-2 [4161 kB]
Get:21 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libglpk-dev amd64 4.65-2 [445 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 10.2 MB in 0s (36.1 MB/s)
Selecting previously unselected package libsuitesparseconfig5:amd64.
(Reading database ... 196191 files and directories currently installed.)
Preparing to unpack .../00-libsuitesparseconfig5_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libsuitesparseconfig5:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libamd2:amd64.
Preparing to unpack .../01-libamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libbtf1:amd64.
Preparing to unpack .../02-libbtf1_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libbtf1:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libcamd2:amd64.
Preparing to unpack .../03-libcamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libcamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libccolamd2:amd64.
Preparing to unpack .../04-libccolamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libccolamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libcolamd2:amd64.
Preparing to unpack .../05-libcolamd2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libcolamd2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libmetis5:amd64.
Preparing to unpack .../06-libmetis5_5.1.0.dfsg-5_amd64.deb ...
Unpacking libmetis5:amd64 (5.1.0.dfsg-5) ...
Selecting previously unselected package libcholmod3:amd64.
Preparing to unpack .../07-libcholmod3_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libcholmod3:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libcxsparse3:amd64.
Preparing to unpack .../08-libcxsparse3_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libcxsparse3:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libglpk40:amd64.
Preparing to unpack .../09-libglpk40_4.65-2_amd64.deb ...
Unpacking libglpk40:amd64 (4.65-2) ...
Selecting previously unselected package libgmpxx4ldbl:amd64.
Preparing to unpack .../10-libgmpxx4ldbl_2%3a6.2.0+dfsg-4_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.2.0+dfsg-4) ...
Selecting previously unselected package libgmp-dev:amd64.
Preparing to unpack .../11-libgmp-dev_2%3a6.2.0+dfsg-4_amd64.deb ...
Unpacking libgmp-dev:amd64 (2:6.2.0+dfsg-4) ...
Selecting previously unselected package libgraphblas3:amd64.
Preparing to unpack .../12-libgraphblas3_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libgraphblas3:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libklu1:amd64.
Preparing to unpack .../13-libklu1_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libklu1:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libldl2:amd64.
Preparing to unpack .../14-libldl2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libldl2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libmongoose2:amd64.
Preparing to unpack .../15-libmongoose2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libmongoose2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libumfpack5:amd64.
Preparing to unpack .../16-libumfpack5_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libumfpack5:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package librbio2:amd64.
Preparing to unpack .../17-librbio2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking librbio2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libspqr2:amd64.
Preparing to unpack .../18-libspqr2_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libspqr2:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libsuitesparse-dev:amd64.
Preparing to unpack .../19-libsuitesparse-dev_1%3a5.7.1+dfsg-2_amd64.deb ...
Unpacking libsuitesparse-dev:amd64 (1:5.7.1+dfsg-2) ...
Selecting previously unselected package libglpk-dev:amd64.
Preparing to unpack .../20-libglpk-dev_4.65-2_amd64.deb ...
Unpacking libglpk-dev:amd64 (4.65-2) ...
Setting up libgraphblas3:amd64 (1:5.7.1+dfsg-2) ...
Setting up libldl2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libmetis5:amd64 (5.1.0.dfsg-5) ...
Setting up libbtf1:amd64 (1:5.7.1+dfsg-2) ...
Setting up libgmpxx4ldbl:amd64 (2:6.2.0+dfsg-4) ...
Setting up libcxsparse3:amd64 (1:5.7.1+dfsg-2) ...
Setting up libsuitesparseconfig5:amd64 (1:5.7.1+dfsg-2) ...
Setting up librbio2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libamd2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libgmp-dev:amd64 (2:6.2.0+dfsg-4) ...
Setting up libcolamd2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libcamd2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libmongoose2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libglpk40:amd64 (4.65-2) ...
Setting up libklu1:amd64 (1:5.7.1+dfsg-2) ...
Setting up libccolamd2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libcholmod3:amd64 (1:5.7.1+dfsg-2) ...
Setting up libspqr2:amd64 (1:5.7.1+dfsg-2) ...
Setting up libumfpack5:amd64 (1:5.7.1+dfsg-2) ...
Setting up libsuitesparse-dev:amd64 (1:5.7.1+dfsg-2) ...
Setting up libglpk-dev:amd64 (4.65-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[2021-07-07T10:04:19.361143394+0000] Execute script: packages/build/rsvg.sh
+ set -e
+ apt-get update -qq
+ apt-get install -y librsvg2-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0
  libgdk-pixbuf2.0-dev libgirepository-1.0-1
Suggested packages:
  librsvg2-doc
The following NEW packages will be installed:
  gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0
  libgdk-pixbuf2.0-dev libgirepository-1.0-1 librsvg2-dev
0 upgraded, 7 newly installed, 0 to remove and 57 not upgraded.
Need to get 330 kB of archives.
After this operation, 1759 kB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libgirepository-1.0-1 amd64 1.64.1-1~ubuntu20.04.1 [85.7 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 gir1.2-glib-2.0 amd64 1.64.1-1~ubuntu20.04.1 [134 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 gir1.2-freedesktop amd64 1.64.1-1~ubuntu20.04.1 [19.2 kB]
Get:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 gir1.2-gdkpixbuf-2.0 amd64 2.40.0+dfsg-3ubuntu0.2 [8268 B]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 gir1.2-rsvg-2.0 amd64 2.48.9-1ubuntu0.20.04.1 [8080 B]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libgdk-pixbuf2.0-dev amd64 2.40.0+dfsg-3ubuntu0.2 [43.6 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 librsvg2-dev amd64 2.48.9-1ubuntu0.20.04.1 [31.5 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 330 kB in 0s (10.1 MB/s)
Selecting previously unselected package libgirepository-1.0-1:amd64.
(Reading database ... 196426 files and directories currently installed.)
Preparing to unpack .../0-libgirepository-1.0-1_1.64.1-1~ubuntu20.04.1_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.64.1-1~ubuntu20.04.1) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../1-gir1.2-glib-2.0_1.64.1-1~ubuntu20.04.1_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.64.1-1~ubuntu20.04.1) ...
Selecting previously unselected package gir1.2-freedesktop:amd64.
Preparing to unpack .../2-gir1.2-freedesktop_1.64.1-1~ubuntu20.04.1_amd64.deb ...
Unpacking gir1.2-freedesktop:amd64 (1.64.1-1~ubuntu20.04.1) ...
Selecting previously unselected package gir1.2-gdkpixbuf-2.0:amd64.
Preparing to unpack .../3-gir1.2-gdkpixbuf-2.0_2.40.0+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking gir1.2-gdkpixbuf-2.0:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
Selecting previously unselected package gir1.2-rsvg-2.0:amd64.
Preparing to unpack .../4-gir1.2-rsvg-2.0_2.48.9-1ubuntu0.20.04.1_amd64.deb ...
Unpacking gir1.2-rsvg-2.0:amd64 (2.48.9-1ubuntu0.20.04.1) ...
Selecting previously unselected package libgdk-pixbuf2.0-dev:amd64.
Preparing to unpack .../5-libgdk-pixbuf2.0-dev_2.40.0+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking libgdk-pixbuf2.0-dev:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
Selecting previously unselected package librsvg2-dev:amd64.
Preparing to unpack .../6-librsvg2-dev_2.48.9-1ubuntu0.20.04.1_amd64.deb ...
Unpacking librsvg2-dev:amd64 (2.48.9-1ubuntu0.20.04.1) ...
Setting up libgirepository-1.0-1:amd64 (1.64.1-1~ubuntu20.04.1) ...
Setting up gir1.2-glib-2.0:amd64 (1.64.1-1~ubuntu20.04.1) ...
Setting up gir1.2-freedesktop:amd64 (1.64.1-1~ubuntu20.04.1) ...
Setting up gir1.2-gdkpixbuf-2.0:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
Setting up libgdk-pixbuf2.0-dev:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
Setting up gir1.2-rsvg-2.0:amd64 (2.48.9-1ubuntu0.20.04.1) ...
Setting up librsvg2-dev:amd64 (2.48.9-1ubuntu0.20.04.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[2021-07-07T10:04:22.043379995+0000] Execute script: packages/build/V8.sh
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libc-ares2 libnode64 libuv1 libuv1-dev
The following NEW packages will be installed:
  libc-ares2 libnode-dev libnode64 libuv1 libuv1-dev
0 upgraded, 5 newly installed, 0 to remove and 57 not upgraded.
Need to get 6357 kB of archives.
After this operation, 25.3 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libuv1 amd64 1.34.2-1ubuntu1.1 [80.4 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libuv1-dev amd64 1.34.2-1ubuntu1.1 [103 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libc-ares2 amd64 1.15.0-1build1 [37.8 kB]
Get:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libnode64 amd64 10.19.0~dfsg-3ubuntu1 [5765 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libnode-dev amd64 10.19.0~dfsg-3ubuntu1 [370 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 6357 kB in 0s (56.9 MB/s)
Selecting previously unselected package libuv1:amd64.
(Reading database ... 196510 files and directories currently installed.)
Preparing to unpack .../libuv1_1.34.2-1ubuntu1.1_amd64.deb ...
Unpacking libuv1:amd64 (1.34.2-1ubuntu1.1) ...
Selecting previously unselected package libuv1-dev:amd64.
Preparing to unpack .../libuv1-dev_1.34.2-1ubuntu1.1_amd64.deb ...
Unpacking libuv1-dev:amd64 (1.34.2-1ubuntu1.1) ...
Selecting previously unselected package libc-ares2:amd64.
Preparing to unpack .../libc-ares2_1.15.0-1build1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.15.0-1build1) ...
Selecting previously unselected package libnode64:amd64.
Preparing to unpack .../libnode64_10.19.0~dfsg-3ubuntu1_amd64.deb ...
Unpacking libnode64:amd64 (10.19.0~dfsg-3ubuntu1) ...
Selecting previously unselected package libnode-dev:amd64.
Preparing to unpack .../libnode-dev_10.19.0~dfsg-3ubuntu1_amd64.deb ...
Unpacking libnode-dev:amd64 (10.19.0~dfsg-3ubuntu1) ...
Setting up libc-ares2:amd64 (1.15.0-1build1) ...
Setting up libuv1:amd64 (1.34.2-1ubuntu1.1) ...
Setting up libnode64:amd64 (10.19.0~dfsg-3ubuntu1) ...
Setting up libuv1-dev:amd64 (1.34.2-1ubuntu1.1) ...
Setting up libnode-dev:amd64 (10.19.0~dfsg-3ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[2021-07-07T10:04:24.129392102+0000] Execute script: packages/build/gert.sh
+ set -e
++ lsb_release -cs
+ OS_CODENAME=focal
+ '[' focal == xenial ']'
+ apt-get update -qq
+ apt-get install -y libgit2-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libgcrypt20-dev libgit2-28 libgpg-error-dev libhttp-parser-dev
  libmbedcrypto3 libmbedtls-dev libmbedtls12 libmbedx509-0 libssh2-1-dev
Suggested packages:
  libgcrypt20-doc libmbedtls-doc
The following NEW packages will be installed:
  libgcrypt20-dev libgit2-28 libgit2-dev libgpg-error-dev libhttp-parser-dev
  libmbedcrypto3 libmbedtls-dev libmbedtls12 libmbedx509-0 libssh2-1-dev
0 upgraded, 10 newly installed, 0 to remove and 57 not upgraded.
Need to get 2646 kB of archives.
After this operation, 11.1 MB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libgpg-error-dev amd64 1.37-1 [109 kB]
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 libgcrypt20-dev amd64 1.8.5-5ubuntu1 [470 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedcrypto3 amd64 2.16.4-1ubuntu2 [150 kB]
Get:4 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedx509-0 amd64 2.16.4-1ubuntu2 [42.3 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedtls12 amd64 2.16.4-1ubuntu2 [71.8 kB]
Get:6 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libgit2-28 amd64 0.28.4+dfsg.1-2 [403 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libmbedtls-dev amd64 2.16.4-1ubuntu2 [444 kB]
Get:8 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libssh2-1-dev amd64 1.8.0-2.1build1 [244 kB]
Get:9 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libhttp-parser-dev amd64 2.9.2-2 [20.2 kB]
Get:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 libgit2-dev amd64 0.28.4+dfsg.1-2 [691 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2646 kB in 0s (35.4 MB/s)
Selecting previously unselected package libgpg-error-dev.
(Reading database ... 196656 files and directories currently installed.)
Preparing to unpack .../0-libgpg-error-dev_1.37-1_amd64.deb ...
Unpacking libgpg-error-dev (1.37-1) ...
Selecting previously unselected package libgcrypt20-dev.
Preparing to unpack .../1-libgcrypt20-dev_1.8.5-5ubuntu1_amd64.deb ...
Unpacking libgcrypt20-dev (1.8.5-5ubuntu1) ...
Selecting previously unselected package libmbedcrypto3:amd64.
Preparing to unpack .../2-libmbedcrypto3_2.16.4-1ubuntu2_amd64.deb ...
Unpacking libmbedcrypto3:amd64 (2.16.4-1ubuntu2) ...
Selecting previously unselected package libmbedx509-0:amd64.
Preparing to unpack .../3-libmbedx509-0_2.16.4-1ubuntu2_amd64.deb ...
Unpacking libmbedx509-0:amd64 (2.16.4-1ubuntu2) ...
Selecting previously unselected package libmbedtls12:amd64.
Preparing to unpack .../4-libmbedtls12_2.16.4-1ubuntu2_amd64.deb ...
Unpacking libmbedtls12:amd64 (2.16.4-1ubuntu2) ...
Selecting previously unselected package libgit2-28:amd64.
Preparing to unpack .../5-libgit2-28_0.28.4+dfsg.1-2_amd64.deb ...
Unpacking libgit2-28:amd64 (0.28.4+dfsg.1-2) ...
Selecting previously unselected package libmbedtls-dev:amd64.
Preparing to unpack .../6-libmbedtls-dev_2.16.4-1ubuntu2_amd64.deb ...
Unpacking libmbedtls-dev:amd64 (2.16.4-1ubuntu2) ...
Selecting previously unselected package libssh2-1-dev:amd64.
Preparing to unpack .../7-libssh2-1-dev_1.8.0-2.1build1_amd64.deb ...
Unpacking libssh2-1-dev:amd64 (1.8.0-2.1build1) ...
Selecting previously unselected package libhttp-parser-dev.
Preparing to unpack .../8-libhttp-parser-dev_2.9.2-2_amd64.deb ...
Unpacking libhttp-parser-dev (2.9.2-2) ...
Selecting previously unselected package libgit2-dev:amd64.
Preparing to unpack .../9-libgit2-dev_0.28.4+dfsg.1-2_amd64.deb ...
Unpacking libgit2-dev:amd64 (0.28.4+dfsg.1-2) ...
Setting up libhttp-parser-dev (2.9.2-2) ...
Setting up libgpg-error-dev (1.37-1) ...
Setting up libmbedcrypto3:amd64 (2.16.4-1ubuntu2) ...
Setting up libmbedx509-0:amd64 (2.16.4-1ubuntu2) ...
Setting up libmbedtls12:amd64 (2.16.4-1ubuntu2) ...
Setting up libmbedtls-dev:amd64 (2.16.4-1ubuntu2) ...
Setting up libgcrypt20-dev (1.8.5-5ubuntu1) ...
Setting up libssh2-1-dev:amd64 (1.8.0-2.1build1) ...
Setting up libgit2-28:amd64 (0.28.4+dfsg.1-2) ...
Setting up libgit2-dev:amd64 (0.28.4+dfsg.1-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
################################# End Task Log #################################
Error: Unhandled Exception: Child Task 966721641 failed: Error building image: Error fetching PRISMA2020 (0.0.2) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: PRISMA2020 (0.0.2)
In addition: Warning message:
In FUN(X[[i]], ...) :
  Package 'PRISMA2020 0.0.2' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores

________________________________

**Comment by nealhaddaway** [comment]
Holy crap - it just deployed but did this!!
https://estech.shinyapps.io/prisma_flowdiagram/
WTF?

**Comment by nealhaddaway** [comment]
Oh wait - I think some of my libraries are out of date...

**Comment by chriscpritchard** [comment]
I think the first thing would be to revert any repo changes back to HEAD as I think the if statement removal means every time the app runs it tries to install from source (hence the error). `git reset --hard HEAD` gets rid of any changes you've made since your last checkout.

Try re-deploying again, but with package caching disabled

**Comment by nealhaddaway** [comment]
OK, in the mean time I put the source function .R files back into the shinyapp folder and removed the package references (PRISMA2020::). So the app is up-and-running, but not pulling the functions in from GitHub.

I don't know why it's not working for me - I've tried everything I can think of...
________________________________

**Comment by chriscpritchard** [comment]
It's at least functional. I'm free for the next 20 minutes if you want to try debugging over a call (might be easier than this back and forward).

**Comment by nealhaddaway** [comment]
I'm just in a meeting sadly, but I think I need to hand over to someone who knows what they're doing with Shiny... it might be my local settings, so perhaps sharing the login details offline is a better way to go?
________________________________

**Comment by nealhaddaway** [comment]
Or we submit to CRAN now and fix it once it's up?

**Comment by chriscpritchard** [comment]
Fixed now - needs to have the latest version of the library installed by running devtools::install_github('nealhaddaway/PRISMA2020') on the Rstudio computer prior to uploading to shinyapps.
