### ISSUE TITLE
Pull in box texts from CSV file instead of specifying them 'hard' in PRISMA_data()

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/PRISMA2020#15]
Allow users to change the wording of text in boxes by pulling in the text from the relevant column in template.csv instead of having them written into PRISMA_data().

**Comment by nealhaddaway** [comment]
Also add explanatory paragraph to the ShinyApp landing page describing the ability to modify texts.

**Comment by chriscpritchard** [comment]
I think we already do pull in the wording from the CSV file, or at least it works for me.

Wording on shiny:

> This tool allows you to produce a flow diagram for your own review that conforms to the PRISMA2020 Statement. You can provide the numbers in the data entry section of the 'Create flow diagram' tab. Alternatively, to allow for more customisation, you can use the template file below.
> 
> This tool also allows you to download an interactive HTML version of the plot, alongside several other common formats.
> 
> We also provide an R package: PRISMA2020 flow diagram R package on Github.
> 
> Please let us know if you have any feedback or if you encounter an error by creating an issue on GitHub

(changed from email as it makes sense of people to open issues rather than just email one person)

**Comment by nealhaddaway** [comment]
Ooh amazing!
