### ISSUE TITLE
Fix CRAN review comments

### ISSUE THREAD

**Issue by nealhaddaway** [nealhaddaway/PRISMA2020#16]
We've received the following response from manual inspection on CRAN:

Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      PRISMA_add_hyperlink_.Rd: \value

Functions which are supposed to only run interactively (e.g. shiny)
should be wrapped in if(interactive()).
Please replace /dontrun{} with if(interactive()){} if possible,
then users can see that the functions are not intended for use in
scripts / functions that are supposed to run non interactively.

**Comment by nealhaddaway** [comment]
Not sure I understand these... @chriscpritchard

**Comment by chriscpritchard** [comment]
Doesn't look too tricky, I'll take a peek over the weekend.

**Comment by nealhaddaway** [comment]
Awesome, thanks!

Sent from my iPhone

On 9 Jul 2021, at 10:33, Chris Pritchard ***@***.***> wrote:

﻿

Doesn't look too tricky, I'll take a peek over the weekend.
