### ISSUE TITLE
Numeric strings in labels in PRISMA.csv

### ISSUE THREAD

**Issue by chapb** [nealhaddaway/PRISMA2020#23]
Is there any purpose to the numeric strings added to the inst/extdata/PRISMA.csv file?

- "Identification4231412341"
- "Identification of new studies via other methods5235325235"

I've removed them in 6e5708c19a5cb05608171e6f4e23625750be8a62, but have another PR open already; this could be easily added if they are in fact not needed.

**Comment by chriscpritchard** [comment]
I think it was my bad... testing something and forgot to remove, so feel free to add to your new PR. I can test that soon.

**Comment by chapb** [comment]
Done! Should be in #22. 

Thanks! Love the work!
