### ISSUE TITLE
PRISMA_data -> PRISMA_flowdiagram issue

### ISSUE THREAD

**Issue by hjames22** [nealhaddaway/PRISMA2020#28]
Hi, thanks for this package! I've used the ShinyApp before but am excited to be able to integrate this. :) 

I am having a challenging time troubleshooting an issue where PRISMA_data where the boxtext and values are all completed as if they are the first row in the template. Perplexingly, the shiny app works when I upload my completed csv. This leads me to think it's something in my rstudio. Any ideas?

I am not quite sure where to start here - if there is something obvious I have missed please let me know. 

`library(readr)
library(PRISMA2020)

PRISMA <- read_csv("PRISMA.csv")

flow_chart_data <- PRISMA2020::PRISMA_data(PRISMA)

flow_chart <- PRISMA2020::PRISMA_flowdiagram(flow_chart_data)
flow_chart
`

<img width="708" alt="Screen Shot 2022-02-24 at 11 07 16 PM" src="https://user-images.githubusercontent.com/33817941/155670413-d003f7f5-7ac9-4227-b97e-9c9493d44ee4.png">

**Comment by chriscpritchard** [comment]
Hi,

Can you share your CSV file?

Chris

**Comment by hjames22** [comment]
yep - thanks!

[PRISMA.csv](https://github.com/nealhaddaway/PRISMA2020/files/8139455/PRISMA.csv)

**Comment by chriscpritchard** [comment]
Brill I'll have a look but might not be immediately. Can I just check what version you're using - the master branch or one of the releases?

**Comment by hjames22** [comment]
No worries - I'm not in any rush. Can set it aside for a bit. Thanks for your help. I used the CRAN version so i believe v. 0.0.3




0.0.3
--

**Comment by chriscpritchard** [comment]
Hi,

I think it's because you're using `readr` and `read_csv`. Try with just `read.csv` instead.

**Comment by chriscpritchard** [comment]
Closed this, as I tested with 'readr' and 'read_csv' and the issue occurred but didn't using standard 'read.csv'
