### ISSUE TITLE
Issue with PRISMA_data()

### ISSUE THREAD

**Issue by vladaron** [nealhaddaway/PRISMA2020#29]
Hello,

I'm trying to build the flowdiagram from a csv file but the numbers do not match those of my csv file([flow_chart_data.csv](https://github.com/nealhaddaway/PRISMA2020/files/8429136/flow_chart_data.csv)):

![flow](https://user-images.githubusercontent.com/81113744/162034795-0823e9f8-b424-4d36-9fac-0a4bb52150e4.png)

 
It seems that the problem occurs with the PRISMA_data() function as the list that it prints doesn't match my template. Also, when i upload my csv file in the Shiny.app, it works fine...
I'm doing:

flow_data <- read.csv("flow_chart_data.csv")
flow_data <- PRISMA_data(flow_data)
PRISMA_flowdiagram(flow_data1,
                   fontsize = 12,
                   interactive = TRUE,
                   previous = FALSE,
                   other = TRUE)

Thank you for your work !

**Comment by nealhaddaway** [comment]
Hi there,

I don't have any problem when I run your code, but note that your plot code refers to 'flow_data1', not 'flow_data' - is that the issue? It's impossible for other data to be plotted so the only way you could be plotting numbers that aren't in your CSV is if you have underlying data already in your R environment. Can I suggest you clear your environment and try again?

Thanks,
Neal
________________________________
From: vladaron ***@***.***>
Sent: 06 April 2022 17:40
To: nealhaddaway/PRISMA2020 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nealhaddaway/PRISMA2020] Issue with PRISMA_data() (Issue #29)


Hello,

I'm trying to build the flowdiagram from a csv file but the numbers do not match those of my csv file(flow_chart_data.csv<https://github.com/nealhaddaway/PRISMA2020/files/8429136/flow_chart_data.csv>):

[flow]<https://user-images.githubusercontent.com/81113744/162034795-0823e9f8-b424-4d36-9fac-0a4bb52150e4.png>

It seems that the problem occurs with the PRISMA_data() function as the list that it prints doesn't match my template. Also, when i upload my csv file in the Shiny.app, it works fine...
I'm doing:

flow_data <- read.csv("flow_chart_data.csv")
flow_data <- PRISMA_data(flow_data)
PRISMA_flowdiagram(flow_data1,
fontsize = 12,
interactive = TRUE,
previous = FALSE,
other = TRUE)

**Comment by chriscpritchard** [comment]
Closing this now until the author can confirm whether or not the steps suggested by @nealhaddaway  have worked.

**Comment by vladaron** [comment]
Hi !

Sorry for the late answer..
I've tried to clean my R environment but the issue remained.

Thanks,
Vlad

**Comment by nealhaddaway** [comment]
Thanks Vlad - can you check your code and let us know what happens when you the mistake I pointed out? Cheers

**Comment by vladaron** [comment]
Hi,

library(PRISMA2020)
flow_data <- read.csv("flow_chart_data.csv")
flow_data <- PRISMA_data(flow_data)
flow <- PRISMA_flowdiagram(flow_data,
                           fontsize = 12,
                           interactive = TRUE,
                           previous = FALSE,
                           other = TRUE)
PRISMA_save(flow,filename = "flow.png", filetype = "png",overwrite = TRUE)

This is the output:
![flow](https://user-images.githubusercontent.com/81113744/164106625-eec5fed2-0be2-4ded-93e2-791ce0b5caf4.png)

This is what i get from the shiny app:
![prisma(2)](https://user-images.githubusercontent.com/81113744/164106835-81468c9b-71e1-4a2d-8fc4-321e3ee33bdc.png)

This is the .csv file
[flow_chart_data.csv](https://github.com/nealhaddaway/PRISMA2020/files/8516648/flow_chart_data.csv)

Thanks !

**Comment by chriscpritchard** [comment]
What version are you using - the one on CRAN, or the current main / master branch?

**Comment by nealhaddaway** [comment]
I've rerun your code now with your CSV file using both the CRAN version and the GitHub version and I can't replicate your error. It doesn't seem possible to me that the package could be generating new data - the number 7 doesn't occur anywhere in your data - for it to be appearing from the package or elsewhere in the template it would need to be pulled in from the trailing end of a cell with a string (like 'box7'), which seems programmatically impossible.

Can you show us a screen shot of your flow_data object?
________________________________

**Comment by vladaron** [comment]
Like so ?

<img width="1277" alt="flow_data_shot1" src="https://user-images.githubusercontent.com/81113744/164169231-461c4b67-2148-4739-b520-c1e5b634dbf5.png">
<img width="1229" alt="flow_data_shot2" src="https://user-images.githubusercontent.com/81113744/164169242-fb8e6cf2-31ba-4dd2-9b8c-a8ae8ce1c3e9.png">

Thanks !

Cheers,
Vlad

**Comment by nealhaddaway** [comment]
Thanks - yeah. That's SO bizarre. Do you have time to hop onto a Zoom call for a screenshare so I can try to get to the bottom of it?
thanks so much
________________________________

**Comment by vladaron** [comment]
Yes

**Comment by nealhaddaway** [comment]
Ace, thanks. Do you have a private means of communication to set up a zoom link?
________________________________

**Comment by vladaron** [comment]
You can send me an email: gglsheetmail@gmail.com

**Comment by chriscpritchard** [comment]
Did this get resolved?

**Comment by nealhaddaway** [comment]
I don’t think so…

Sent from my iPhone

On 7 May 2022, at 06:32, Chris Pritchard ***@***.***> wrote:

﻿

Did this get resolved?

**Comment by nealhaddaway** [comment]
That works on my machine after reinstalling, and @chriscpritchard doesn't seem to be able to replicate it either - I'm afraid it sounds like you have a problem with your machine/installation of R. I don't know what to suggest I'm afraid, but I don't think there's a bug with the package. @chriscpritchard - any suggestions?

**Comment by nealhaddaway** [comment]
Can you import the CSV into R and show us a screenshot of the previewed data? 

File > Import Dataset > From text (base)

Scroll right and show the data as it's being read in on your machine.

**Comment by vladaron** [comment]
Hi,

Here it is
<img width="638" alt="Screenshot 2022-05-11 at 15 46 36" src="https://user-images.githubusercontent.com/81113744/167865195-d3d9c8ad-b429-4840-bd16-11605cab8aff.png">

**Comment by nealhaddaway** [comment]
Can you jump on a call now? https://meet.google.com/zos-jiua-nfw

**Comment by nealhaddaway** [comment]
Dodgy internet actually. The only thing I can suggest is to take the function code for PRISMA_data() and run it line by line on your input to see where it's going wrong.

**Comment by vladaron** [comment]
Hi !
Ok I'll give it a try

**Comment by vladaron** [comment]
Hi !

I've updated both R and Rstudio and now it works fine.

Cheers,
V.

**Comment by nealhaddaway** [comment]
Great! Thanks - glad it wasn’t a bug :)

Sent from my iPhone

On 17 May 2022, at 22:34, vladaron ***@***.***> wrote:

﻿

Hi !

I've updated both R and Rstudio and now it works fine.

Cheers,
V.
