### ISSUE TITLE
Remove need to attach() data

### ISSUE THREAD

**Issue by mcguinlu** [nealhaddaway/PRISMA2020#3]
Hi @nealhaddaway, 

Prompted by a user I recommended the package to missing the `attach()` step and getting a non-informative error, it might be worth reassessing the need for users to `attach()` the data before they can run `PRISMA_flowchart()`. It would be better to explicitly refer to objects within the `PRISMA_flowchart()` function using `$` rather than the current set-up (e.g. so `tooltips` becomes `data$tooltips`). [**I imagine this is a hang-over from the old way the function inputs were defined, and is on the to-do list, but wanted to formally flag it** 😀]

Some more relevant info on why `attach()` can be dangerous here, in case it's useful: https://www.r-bloggers.com/2011/05/to-attach-or-not-attach-that-is-the-question/

**Comment by nealhaddaway** [comment]
Yes!! Working on this...
