### ISSUE TITLE
Standardise function names

### ISSUE THREAD

**Issue by mcguinlu** [nealhaddaway/PRISMA2020#6]
Given that a naming convention has begun naturally, I think we should retrospecitvely apply it to the other two functions:

E.g. 
- `PRISMA_flowdiagram()` (no change)

- `PRISMA_save()` (no change)

- `read_PRISMAdata()` -> `PRISMA_data()`

- `sr_flow_interactive()` -> `PRISMA_interactive()`

**Comment by nealhaddaway** [comment]
This all sounds amazing - thanks so much, both! Sorry, I'm still rather swamped.
Many thanks indeed!
Neal
________________________________
