### ISSUE TITLE
Question: How to rotate labels?

### ISSUE THREAD

**Issue by SHogenboom** [nealhaddaway/PRISMA2020#8]
Hi, 
Thanks for your awesome efforts in creating this elaborate diagram / PRISMA flowchart! I've been using your code as inspiration for a graph/flowchart I'm trying to create myself. 

I've looked at your code numerous times but cannot figure out how you managed to have the "Identification", "Screening", and "Included" labels to become rotated. I really like this way of identifying the phases of the review, but find it difficult to replicate. Could you perhaps elaborate on how you managed to do this? Or point me towards where you coded this?

Thanks!
Sally

**Comment by chriscpritchard** [comment]
It was in bug #2 and PR #4 where we discussed this, hope this helps!
